# Generated by Django 4.0.5 on 2022-07-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qaydlar',
            name='muhim',
            field=models.CharField(max_length=15),
        ),
    ]
